development:
  adapter:  postgresql
  encoding: unicode
  database: localization_tracker_development
  pool: 5
  user: postgres
  password: postgres

test:
  adapter:  postgresql
  encoding: unicode
  database: localization_tracker_test
  pool: 5
  user: postgres
  password: postgres
